export const SET_CONFIGURATION = 'SET_CONFIGURATION';

export const SET_CURRENT_SHOW_ID = 'SET_CURRENT_SHOW_ID';
export const SET_CURRENT_SHOW = 'SET_CURRENT_SHOW';
export const CLEAR_CURRENT_SHOW_DATA = 'CLEAR_CURRENT_SHOW_DATA';

export const ADD_OR_REMOVE_FAVORITE = 'ADD_OR_REMOVE_FAVORITE';
export const ADD_OR_REMOVE_WATCHED_EPISODE = 'ADD_OR_REMOVE_WATCHED_EPISODE';
export const MARK_ALL_EPISODE_WATCHED = 'MARK_ALL_EPISODE_WATCHED';
export const ADD_EPISODES_TO_SHOW = 'ADD_EPISODES_TO_SHOW';
export const SET_EPISODES_IN_SEASON = 'SET_EPISODES_IN_SEASON';
export const REPLACE_FAVORITES = 'REPLACE_FAVORITES';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
export const SAVE_FAVORITES_TO_CLOUD = 'SAVE_FAVORITES_TO_CLOUD';

// export const GET_FAVORITES_FROM_CLOUD = 'GET_FAVORITES_FROM_CLOUD';
// export const SET_FAVORITES_TO_CLOUD = 'SET_FAVORITES_TO_CLOUD';
// export const SET_UPDATE_DATE = 'SET_UPDATE_DATE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
