export const SET_CONFIGURATION = 'SET_CONFIGURATION';
export const SET_CURRENT_SHOW_ID = 'SET_CURRENT_SHOW_ID';
export const SET_CURRENT_SHOW = 'SET_CURRENT_SHOW';
export const ADD_OR_REMOVE_FAVORITE = 'ADD_OR_REMOVE_FAVORITE';
export const ADD_OR_REMOVE_WATCHED_EPISODE = 'ADD_OR_REMOVE_WATCHED_EPISODE';
export const MARK_ALL_EPISODE_WATCHED = 'MARK_ALL_EPISODE_WATCHED';

